### ISSUE TITLE
No "data" in the bus timings for 0xFE00-0xFFFF

### ISSUE THREAD

**Issue by trekawek** [Gekkio/gb-ctr#2]
In the bus timing diagrams, there's no "data" block for the 0xFE00-0xFFFF range diagrams, both read and write. Is it by mistake, or there's something special about this range and data bits are passed in some other way?

https://github.com/Gekkio/gb-ctr/blob/9bc0999463d37b9a95200423a579b1117e0625a9/appendix/external-bus.tex#L85

https://github.com/Gekkio/gb-ctr/blob/9bc0999463d37b9a95200423a579b1117e0625a9/appendix/external-bus.tex#L156

**Comment by Gekkio** [comment]
That's because CPU memory accesses to that range don't involve the external data bus at all. The address is visible externally, but the GB SoC doesn't assert any chip select signals (CS or A15). Also:

In the case of a read, the SoC doesn't care what happens on the external data bus even if a value was driven there.
In the case of a write, the SoC doesn't put any data on the external data bus.

**Comment by trekawek** [comment]
Thanks for the explanation!
